### ISSUE TITLE
Support for investment into female recruitment / retention at companies [5pts]

### ISSUE THREAD

**Issue by yaelabadi** [danmek/Gender-Equity-4-Policy#8]
**As** tech companies, that are suffering from a lack of Women in STEM and are making many efforts to be attractive for women, 

**we want** arguments and evidence to support management decisions to invest into female recruitment and retention

**so that** they could take a bigger part in the workforce and be promoted as men.

**Comment by danmek** [comment]
## INVEST
- [x] Independent
- [x] Negotiable
- [x] Valuable
[Maybe?] Estimable - unclear which arguments exactly would be valuable
[Maybe?] Small
- [x] Testable

## TASKS
- Identify what kinds of arguments / evidence companies need on female recruitment and retention (e.g., "highly educated careerwomen still spend disproportionate amounts of time on household)
- Identify datasets that will support above arguments
- Clean above dataset into a format that can be visualized or analyzed easily
- Sketch out potential visualizations (by hand or excel)
- Develop text content to accompany visualization
- Develop a blank HTML website
- Show visualization and text on website

## DEFINITION OF DONE
- Show to a tech company - ask if this is valuable evidence to support management decisions to invest into female recruitment and retention

**Comment by danmek** [comment]
*Poker planning insights* [5pts]

MVP:
- study and analyze data that could address this user story

**Comment by kellyyun** [comment]
- [Women in tech statistics](https://www.cio.com/article/201905/women-in-tech-statistics-the-hard-truths-of-an-uphill-battle.html) - more than the data itself, the way this article is structured provides list of gaps for women in stem (e.g. employment rate, salary, degree, workplace culture, retention, representation, pandemic, founder/leadership status)
- [Women in Tech: The Facts](https://wpassets.ncwit.org/wp-content/uploads/2021/05/13193304/ncwit_women-in-it_2016-full-report_final-web06012016.pdf) - provides a good content for the narrative 
- Pew Research (report attached) - I mined some of the better infographics attached her as well
- [Stopping the Exodus of Women in Science](https://hbr.org/2008/06/stopping-the-exodus-of-women-in-science) - image from this article attached
- [How CIOs recruit and retain experienced women in tech](https://www2.deloitte.com/us/en/insights/topics/value-of-diversity-and-inclusion/diversity-and-inclusion-in-tech/recruit-and-retain-experienced-women-in-technology.html) - some great images and content from Deloitte 

![why female attrition is important - HBR](https://user-images.githubusercontent.com/97000774/148707601-2cb9cc1f-b7b5-4c99-96d6-688dc607f045.png)
<img width="420" alt="earnings in stem by demographic - pew research" src="https://user-images.githubusercontent.com/97000774/148707603-a4ce092e-c1a1-466a-8b62-5741f6d901b8.png">
![Work discrimination in STEM by gender - pew research](https://user-images.githubusercontent.com/97000774/148707604-331f2dcc-3c99-4485-985f-26e6bc29e664.png)
[Pew Research diversity in stem report from 2021.pdf](https://github.com/danmek/Gender-Equity-4-Policy/files/7836308/Pew.Research.diversity.in.stem.report.from.2021.pdf)
![Women in tech attrition - Deloitte image](https://user-images.githubusercontent.com/97000774/148707605-6b569238-0bc6-447c-8ed2-709875042512.png)
![top reported barriers to leadership roles - Deloitte image](https://user-images.githubusercontent.com/97000774/148707607-c5aa5d00-83a9-4c2f-9735-9cd19ecc26b1.png)
<img width="420" alt="Representation of women in stem - pew research" src="https://user-images.githubusercontent.com/97000774/148707608-5cd3a955-1652-4cd7-b863-4d5d4225165a.png">

**Comment by julihcho** [comment]
Kelly - thanks a ton for this! As we discussed on Slack, I pivoted to looking more in datasets rather than the arguments, since my research came up with very similar ones. 

I found the raw dataset for the analysis in [this link](https://www.brookings.edu/research/labor-force-nonparticipation-trends-causes-and-policy-solutions/#cancel). It is very interesting & key to our thesis, but data looks tricky. 

I've added the datasets, and summarized potential takeaways & problems with data analysis [here](https://github.com/danmek/Gender-Equity-4-Policy/tree/data-company/data/us_cps).

**Comment by julihcho** [comment]
A few other datasets I've looked at that are simpler tasks but perhaps not as interesting:

* [Enterprise Survey](https://www.enterprisesurveys.org/en/data/exploretopics/gender) - fewer women own / manage enterprises across the world 
* [MSME finance gap](https://www.smefinanceforum.org/data-sites/msme-finance-gap) - though the number of firms that lack access to finance is comparable across genders, the actual $ amount female-owned firms need is larger. 

I've also looked at some cross-country data on businesses / enterprises. These look like it may overlap with @danmek 's user story as well:
* [Entrepreneurs](https://data.oecd.org/entrepreneur/self-employed-with-employees.htm#indicator-chart) - women start fewer businesses than men across all countries 
* [Entrepreneurs](https://data.oecd.org/entrepreneur/running-a-business.htm#indicator-chart) - women run fewer businesses than men
* [Gender wage gap](https://data.oecd.org/earnwage/gender-wage-gap.htm) - big surprise here

I'd be curious to see how these datasets plot against the household labor burden or education attainment levels. It'd be interesting if there is a takeaway like "Women still face a high gender wage gap even if they are highly educated, if they face a high household burden." 

This may overlap with Dana's workstream - will check in tomorrow before working on that.

**Comment by julihcho** [comment]
A few more thoughts:

TDLR:
* Data on female employee retention & promotion not publicly available (which makes sense, confidential HR info)
* Easily accessible data exists on gender wage gap, fewer female entrepreneurs, fewer women in top 10 occupations / STEM, fewer women working, regardless of educational attainment 
* Somewhat easily accessible data on companies with women on boards in CA
* Hard to manipulate data on women not being employed for family reasons 

Datasets on female employee promotion & retention is what we need, but most of them are not publicly available:
* [Zoominfo](https://pipeline.zoominfo.com/recruiting/women-promotion-gap)
* [ADP Report](https://www.adp.com/resources/articles-and-insights/adp-research-institute/research-topics/-/media/62FB03253C3B4B80A2EE73EB8EC29B82.ashx)
* [Yale study of retail chain](https://insights.som.yale.edu/insights/women-arent-promoted-because-managers-underestimate-their-potential)
* [Boardlist study of promotions in pandemic](https://www.cnbc.com/2020/10/13/pandemic-fallout-men-got-3-times-more-promotions-than-women.html)

Dataset on women in boards
* [Women on Boards](https://bpd.cdn.sos.ca.gov/women-on-boards/wob-report-2021-02.pdf) - new CA law about female board members on CA publicly traded corporations, started in 2019. Roughly half seem to have women on boards. Could juxtapose against revenue?

Data in the same format as the CPS data above:
* Though more women are working, less women are employed in the top 10 occupations in the last decade [link](https://www.dol.gov/agencies/wb/data/occupations-decades-100)
* Women work more part-time than men [link](https://www.dol.gov/agencies/wb/data/latest-annual-data/full-and-part-time-employment#Percent-distribution-of-workers-employed-full-time-and-part-time-by-sex)
* Mothers work more part-time than men [link](https://www.dol.gov/agencies/wb/data/latest-annual-data/full-and-part-time-employment#Employed-parents-by-full-time-and-part-time-status-sex-and-age-of-youngest-child)
* Mothers work less than men [link](https://www.dol.gov/agencies/wb/data/mothers-and-families) [link](https://www.dol.gov/agencies/wb/data/latest-annual-data/labor-force-participation-rates#Labor-Force-Participation-Rate-of-Mothers-and-Fathers-by-Age-of-Youngest-Child)
* When spouse is present, women work less, though men work more [link](https://www.dol.gov/agencies/wb/data/latest-annual-data/labor-force-participation-rates#Labor-Force-Participation-Rate-of-Mothers-and-Fathers-by-Age-of-Youngest-Child)
* More women are in STEM, but driven by social and life & physical scientists, not engineers or computer occupations [link](https://www.dol.gov/agencies/wb/data/occupations-stem?_ga=2.133821838.1417239898.1641831422-977518972.1641831422)
* Gender wage gap exists across all occupations, even professional occupations [link](https://www.dol.gov/agencies/wb/data/occupations)
* Gender wage gap persistent across all education levels [link](https://www.dol.gov/agencies/wb/data/earnings/Median-weekly-earnings-educational-sex)
* Full datasets [link](https://www.bls.gov/cps/earnings.htm) and [here](https://www.bls.gov/cps/demographics.htm#families)

**Comment by julihcho** [comment]
This user story will be split into two and assigned individual owners:

@julihcho : create new user story around companies looking to support working mothers
@kellyyun : create new user story around companies looking to close the wage gap
